// <auto-generated />
using System;
using EntityFrameworkLab;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFrameworkLab.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityFrameworkLab.Address", b =>
                {
                    b.Property<int>("AddressIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City");

                    b.Property<string>("County");

                    b.Property<string>("House_Name_or_Number");

                    b.Property<string>("Postcode");

                    b.Property<string>("Street");

                    b.HasKey("AddressIdentifier");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("EntityFrameworkLab.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressIdentifier");

                    b.Property<DateTime>("Date_of_Birth");

                    b.Property<string>("First_Name");

                    b.Property<string>("Last_Name");

                    b.Property<string>("Middle_Name");

                    b.HasKey("PersonID");

                    b.HasIndex("AddressIdentifier");

                    b.ToTable("People");
                });

            modelBuilder.Entity("EntityFrameworkLab.Person", b =>
                {
                    b.HasOne("EntityFrameworkLab.Address", "Address")
                        .WithMany("People")
                        .HasForeignKey("AddressIdentifier");
                });
#pragma warning restore 612, 618
        }
    }
}
