// <auto-generated />
using System;
using DistSysLab7;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DistSysLab7.Migrations
{
    [DbContext(typeof(Lab7Context))]
    [Migration("20200305155712_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DistSysLab7.Address", b =>
                {
                    b.Property<int>("AddressIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("House_Name_or_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressIdentifier");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("DistSysLab7.BankAccount", b =>
                {
                    b.Property<int>("AccountIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AccountIdentifier");

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("DistSysLab7.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressIdentifier")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("BankAccountAccountIdentifier")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date_of_Birth")
                        .HasColumnType("datetime2");

                    b.Property<string>("First_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonID");

                    b.HasIndex("AddressIdentifier");

                    b.HasIndex("BankAccountAccountIdentifier");

                    b.ToTable("People");
                });

            modelBuilder.Entity("DistSysLab7.Person", b =>
                {
                    b.HasOne("DistSysLab7.Address", "Address")
                        .WithMany("People")
                        .HasForeignKey("AddressIdentifier");

                    b.HasOne("DistSysLab7.BankAccount", "BankAccount")
                        .WithMany()
                        .HasForeignKey("BankAccountAccountIdentifier");
                });
#pragma warning restore 612, 618
        }
    }
}
